### ISSUE TITLE
pkg_resources.DistributionNotFound:

### ISSUE THREAD

**Issue by abhinavmaury** [skcript/cvscan#22]
While I am running this line 'cvscan parse --name data/sample/lakshmanaram', I keep on getting this error
'pkg_resources.DistributionNotFound: The 'numpy==1.11.3' distribution was not found and is required by cvscan'

Could you help me in this?

**Comment by swaathi** [comment]
@Navdevl Can you help @abhinavmaury?

**Comment by Navdevl** [comment]
`pip install -r requirements.txt `
This will install all the required packages that is needed by CVscan. :)

**Comment by swaathi** [comment]
Thanks @Navdevl. Closing this. Feel free to re-open if you need more help @abhinavmaury.
